# Generated by Django 2.1 on 2018-08-28 18:22

from django.db import migrations, models
import uploadvideos.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadvideos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadvideos',
            name='videofile',
            field=models.FileField(null=True, upload_to=uploadvideos.models.scramble_uploaded_filename, verbose_name=''),
        ),
    ]
