# Generated by Django 2.1 on 2018-08-28 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadvideos', '0002_uploadvideos_videofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadvideos',
            name='desc',
        ),
    ]
