# Generated by Django 2.1 on 2018-08-29 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadvideos', '0003_remove_uploadvideos_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadvideos',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
