# Generated by Django 2.1 on 2018-09-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadvideos', '0006_auto_20180901_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadvideos',
            name='hourvid',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='uploadvideos',
            name='minutevid',
            field=models.IntegerField(default=1),
        ),
    ]
