# Generated by Django 2.1 on 2018-09-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadvideos', '0007_auto_20180901_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadvideos',
            name='positionsdb',
            field=models.CharField(default='{}', max_length=255),
        ),
    ]
