# Generated by Django 2.1 on 2018-09-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadvideos', '0009_auto_20180909_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadvideos',
            name='videoduration',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
