# Generated by Django 2.1 on 2018-09-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadvideos', '0010_uploadvideos_videoduration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadvideos',
            name='videofile',
            field=models.FileField(upload_to=''),
        ),
    ]
