# Generated by Django 2.1 on 2018-09-20 15:40

from django.db import migrations, models
import uploadvideos.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadvideos', '0012_auto_20180918_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadvideos',
            name='videofile',
            field=models.FileField(null=True, upload_to=uploadvideos.models.scramble_uploaded_filename, verbose_name=''),
        ),
    ]
